version: '2'

services:
  nats:
    image: bitnami/nats:latest
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    environment:
      - NATS=10s
    volumes:
      - /Users/yesmanmx/Work/iota/Projects/natsdemo/nats-server.conf:/bitnami/nats/conf/nats-server.conf:ro
